justfile

This is a partial revert from commit 95db98f0a706 ("justfile: Remove references to dev-env container"): Re-add the justfile targets for mounting, unmounting, and allocating hugepages. These targets would have been useful a couple of times over the last days.
Also add two justfile targets, setup-test-env and teardown-test-env, to call these hugepages-related private targets.

justfile: Re-add hugepage-related targets

---

design-docs/src/mdbook/src/build/index.md

Document the various repositories that we're using at the moment for dataplane and control plane.
These are not meant to be user docs, but rather some notes to help newcomers understand how the code base is laid out.
Fixes: #158

docs: Add notes on repositories architecture

---

deny.toml

This seems to have been fixed for a while

Remove syn exception in deny.toml

---

dpdk/src/mem.rs
justfile
net/Cargo.toml
net/src/eth/ethertype.rs
net/src/eth/mac.rs
net/src/eth/mod.rs
net/src/icmp4/mod.rs
net/src/icmp6/mod.rs
net/src/ip/mod.rs
net/src/ipv4/addr.rs
net/src/ipv4/dscp.rs
net/src/ipv4/ecn.rs
net/src/ipv4/frag_offset.rs
net/src/ipv4/mod.rs
net/src/ipv6/addr.rs
net/src/ipv6/flow_label.rs
net/src/ipv6/mod.rs
net/src/packet.rs
net/src/tcp/checksum.rs
net/src/tcp/mod.rs
net/src/tcp/port.rs
net/src/udp/checksum.rs
net/src/udp/mod.rs
net/src/udp/port.rs
net/src/vlan/mod.rs
net/src/vxlan/mod.rs
net/src/vxlan/vni.rs

This PR significantly expands the ability to manipulate packets.
We are not quite to a stable(ish) API yet, but we are getting there.

Pr/daniel noland/parser part 2

---

dataplane/src/main.rs

- **dp: Split main() function into EAL init, devices init, workers start**
- **nat: Split out Vpc, Pif, PrefixTrie from nat module**
First commit splits the `main()` function into different blocks to make it easier to read, and work with.
Second commit splits some components used in the NAT module out of that module, and into their respective new modules, `vpc` and `vpc::prefix_trie`, in order to make them accessible to separate modules from the dataplane.

Reorganise NAT elements, main() function

---

net/src/udp/mod.rs
net/src/udp/port.rs

Minor fixups for udp parse logic and tests

Fixups for UDP parse

---

net/src/eth/mac.rs

We have checks, may as well use them.

Improve src/dst mac generation

---

Cargo.lock
Cargo.toml
dataplane/Cargo.toml

Clean up Cargo.toml to make it more consistent.

Clean up Cargo.toml

---

Cargo.lock
Cargo.toml
deny.toml
errno/Cargo.toml
routing/Cargo.toml
routing/src/display.rs
routing/src/vrf.rs

Hopefully this calms cargo deny down for @Fredi-raspall

Tame cargo deny

---

net/src/vlan/mod.rs

Focused fuzzers for Vlan

---

dpdk/src/mem.rs
net/Cargo.toml
net/src/buffer/mod.rs
net/src/buffer/test_buffer.rs
net/src/lib.rs

These traits / structs allow a "bring your own packet" model, which should help a lot with testing.

feat(net): Introduce PacketBuffer

---

.github/workflows/dev.yml
.github/workflows/docs.yml
.github/workflows/lint-just-fmt.yml
.github/workflows/sterile.yml
justfile

Boring cleanup of our build system.
This took a while, but it is likely worth it to maintain a healthy build system.

Clean up justfile

---

dataplane/src/main.rs
routing/src/nexthop.rs
routing/src/vrf.rs

* Silence clippy warnings in routing
* Silence clippy routing in main

Silence clippy warnings

---

.github/dependabot.yml

I wish there was an easier way to test this file before it hits main.
See [d59b3d3b963adca424766244ce643ec3db693f2b](https://github.com/githedgehog/dataplane/pull/274/commits/a41d16df37b2c9da570988df4959a4e8c489ded3) for the commit which introduced this bug.

fix(dependabot): incorrect syntax

---

.github/dependabot.yml

Dependabot fix (again)

---

.github/dependabot.yml
.github/workflows/bump.yml

Once again, I try to calm dependabot.
Mostly by depending on it for less.

Bump 2: electric boogaloo 

---

dataplane/src/args.rs
dataplane/src/main.rs
dataplane/src/nat.rs
dataplane/src/packet.rs

- **chore(dataplane): Fix pedantic Clippy warnings**
- **chore(dataplane): Deny pedantic Clippy warnings for dataplane package**

Fix Clippy's pedantic reports in dataplane package

---

dataplane/src/main.rs
dataplane/src/pipeline/dyn_nf.rs
dataplane/src/pipeline/mod.rs
dataplane/src/pipeline/static_nf.rs
dpdk/src/dev.rs
dpdk/src/eal.rs
dpdk/src/flow/mod.rs
dpdk/src/lib.rs
dpdk/src/mem.rs
dpdk/src/socket.rs
rust-toolchain.toml

Fixing the CI pipeline.
#319 caused a regression.
This reverts that (on top of @qmonnet's #325 )
If this is merged then #325 should be closed.
If #325 is merged then this should be closed.

remove rust-toolchain.yml

---

dataplane/src/main.rs
dataplane/src/packet.rs
dataplane/src/packet_meta.rs
routing/src/lib.rs

~~.. on top of https://github.com/githedgehog/dataplane/pull/290.~~

Add packet metadata

---

Cargo.lock
Cargo.toml
dataplane/Cargo.toml
dataplane/src/main.rs
dataplane/src/packet_hash.rs

@daniel-noland I was going to move Packet to a separate crate (having packet_metadata and this new packet_hash as submodules), but did not do that since I remembered you saying that you had that change in a separate branch.

Simple packet hash for ip traffic

---

.github/workflows/bump.yml

- **ci(bump): Remove installation of cargo-upgrades**
- **ci(bump): Rework cargo upgrades**

CI: In bump.yml, remove unused dep, rework cargo upgrades step to split PRs into individual upgrade commits

---

dpdk-sys/Cargo.toml
id/Cargo.toml
justfile
pipeline/Cargo.toml

See #362 for context, and individual commit description for details on this PR.

Fix and re-enable doctests execution

---

Cargo.lock
Cargo.toml
dataplane/Cargo.toml
dataplane/src/args.rs
dataplane/src/drivers/dpdk.rs
dataplane/src/drivers/kernel.rs
dataplane/src/drivers/mod.rs
dataplane/src/main.rs
deny.toml

Rides on https://github.com/githedgehog/dataplane/pull/369
* Requires privileges
* If you wan to give it a try:
```
sudo ./target/x86_64-unknown-linux-gnu/debug/dataplane --driver kernel --interface any
```

Kernel Driver

---

net/src/packet/display.rs

on https://github.com/githedgehog/dataplane/pull/381
Small changes to make Packet dumps easier to read.

feat(net): clean up & improve Packet display

---

Cargo.lock
Cargo.toml
clippy.toml
dataplane/src/drivers/dpdk.rs
dataplane/src/main.rs
id/src/lib.rs
net/Cargo.toml
net/src/eth/ethtype.rs
net/src/eth/mac.rs
net/src/interface/mod.rs
net/src/lib.rs
net/src/packet/mod.rs
net/src/vlan/mod.rs
net/src/vxlan/vni.rs

Prep for interface manager
I suspect these changes are non controversial so I'm putting them up for early review.
Hopefully that makes the actual interface manager review less horrible.  No promises tho :woman_shrugging:

Minor cleanup

---

.github/workflows/bump.yml

- **ci: Don't error out of "bump" workflow when log file cannot be removed**
- **ci: In "bump" workflow, remove log files when exiting early**

ci: Fixes for "bump" workflow

---

id/src/lib.rs

I realized that the requirement to use a type alias hack in the id crate is fundamentally stemming from failing to put the `?Sized` bound on the phantom type.
This commit reworks that crate and significantly reduces its complexity.

fix: rework id crate

---

Cargo.toml
net/Cargo.toml

@Fredi-raspall reported some build failures the other day.
I noticed them as well.  I believe this is the fix.

Fix build options

---

Cargo.lock
Cargo.toml
net/Cargo.toml
net/src/eth/mac.rs
net/src/interface/bridge.rs
net/src/interface/mod.rs
net/src/interface/vrf.rs
net/src/interface/vtep.rs
net/src/ipv4/addr.rs
net/src/lib.rs
net/src/route/mod.rs
net/src/route/table.rs

Part one of the long-awaited interface manager pr.
I expect a part two on top of this shortly.

Interface-manager part 1

---

justfile
routing/src/display.rs
routing/src/prefix.rs
routing/src/vrf.rs
vpc-manager/tests/reconcile.rs

- **style(routing): Fix Clippy reports**
- **build: Allow passing arguments to "just clippy"**

Fix Clippy reports (nightly)

---

mgmt/src/grpc/server.rs
mgmt/src/grpc/test.rs

With the nightly toolchain, Clippy complains about variables that can be used directly in "format!" string and the like. Fix them.
Link: https://github.com/githedgehog/dataplane/actions/runs/14710124839/job/41280152080#step:12:355

style(mgmt): Fix Clippy reports

---

Cargo.lock
Cargo.toml
dataplane/Cargo.toml
dataplane/src/main.rs
mgmt/Cargo.toml
mgmt/src/frr/frrmi/mod.rs
mgmt/src/frr/mod.rs
mgmt/src/grpc/converter.rs
mgmt/src/grpc/mod.rs
mgmt/src/grpc/server.rs
mgmt/src/grpc/test.rs
mgmt/src/models/external/configdb/gwconfig.rs
mgmt/src/models/external/configdb/gwconfigdb.rs
mgmt/src/models/external/mod.rs
mgmt/src/models/external/overlay/mod.rs
mgmt/src/models/internal/device/mod.rs
mgmt/src/models/internal/routing/bgp.rs
mgmt/src/processor/confbuild.rs
mgmt/src/processor/mod.rs
mgmt/src/processor/namegen.rs
mgmt/src/processor/proc.rs
mgmt/src/processor/tests.rs

This rides on https://github.com/githedgehog/dataplane/pull/427

Management integration

---

mgmt/src/frr/renderer/prefixlist.rs
mgmt/src/frr/renderer/routemap.rs
mgmt/src/models/external/overlay/mod.rs
mgmt/src/processor/confbuild.rs
mgmt/src/processor/namegen.rs

Make sure that there is no inconsistency on name cases by ensuring upper case by construction.

feat(mgmt): ensure name consistency

---

net/src/ipv4/mod.rs

Targets https://github.com/githedgehog/dataplane/pull/509

Update IP checksum when decrementing TTL

---

net/src/ipv4/mod.rs
net/src/packet/hash.rs
net/src/packet/mod.rs
net/src/vxlan/encap.rs

Targets https://github.com/githedgehog/dataplane/pull/513

Small VxLAN API change

---

routing/src/prefix.rs

Quentin's revert of one of my prior changes introduced some duplicate implementation.  This unifies that duplication.

chore(routing): Unify string -> Prefix implementations

---

dataplane/src/packet_processor/ipforward.rs
net/src/buffer/test_buffer.rs
net/src/checksum.rs
net/src/headers.rs
net/src/icmp4/checksum.rs
net/src/icmp4/mod.rs
net/src/icmp6/checksum.rs
net/src/icmp6/mod.rs
net/src/ipv4/checksum.rs
net/src/ipv4/mod.rs
net/src/ipv6/mod.rs
net/src/lib.rs
net/src/packet/display.rs
net/src/packet/hash.rs
net/src/packet/meta.rs
net/src/packet/mod.rs
net/src/packet/test_utils.rs
net/src/tcp/checksum.rs
net/src/tcp/mod.rs
net/src/tcp/port.rs
net/src/udp/checksum.rs
net/src/udp/mod.rs

Rushed PR to add support for checksum updates.
This is missing the type of testing I would normally write.  Instead only smoke tests are included.

checksum updates

---

mgmt/src/models/external/gwconfig/mod.rs
mgmt/src/processor/confbuild.rs

Small changes to relax vtep constraints to allow non-vpc configs.

Fix validation vtep

---

Cargo.lock
Cargo.toml
interface-manager/src/interface/mod.rs
interface-manager/src/lib.rs
interface-manager/src/tc/README.md
interface-manager/src/tc/action/gact.rs
interface-manager/src/tc/action/mirred.rs
interface-manager/src/tc/action/mod.rs
interface-manager/src/tc/action/tunnel_key.rs
interface-manager/src/tc/block.rs
interface-manager/src/tc/chain.rs
interface-manager/src/tc/filter/mod.rs
interface-manager/src/tc/mod.rs
interface-manager/src/tc/qdisc.rs
mgmt/Cargo.toml
net/src/interface/pci/mod.rs

This is a very rushed implementation of tc functionality we will not need for some time.
Due to sudden priority changes, I'm submitting it without the type of testing I would normally add.  Testing this properly requires hardware in CI in any case.
My goal with this PR is to get this functionality merged and integrated so that we avoid losing all of this work as the code changes.
My request for the review here is basically that you flag things you think will be in our way if we merge this.  I expect the remainder of this functionality to go unused for a while.

host gateway part 2

---

dataplane/src/args.rs
dataplane/src/main.rs
dataplane/src/statistics/global_counters.rs
dataplane/src/statistics/mod.rs

- Add per-second counters based on diff between last counters update and current
- Fix minor prometheus handler issues

Adjust metrics with per-second stats, minor fixes

---

dataplane/src/drivers/kernel.rs

Do not panic on poll errors nor in case sockets cannot be created. Also, allow running even if no interface is provided. This allows starting the dataplane for testing without any packet processing.

Small kernel driver enhancements

---

Cargo.lock
Cargo.toml
routing/src/cpi.rs

Adapt code to use dplane-rpc 1.1.2 and respond to a Connect request with a ConnInfo object.

use rpc 1.1.2 & return ConnInfo

---

dataplane/src/packet_processor/ipforward.rs
net/src/packet/meta.rs

Fixes: https://github.com/githedgehog/dataplane/issues/735

Warn about silent, unplanned  packet drops

---

config/src/converters/grpc/underlay.rs
config/src/external/mod.rs
config/src/external/underlay/mod.rs
config/src/internal/interfaces/interface.rs
config/src/internal/mod.rs
mgmt/src/processor/confbuild/internal.rs
mgmt/src/tests/mgmt.rs
nat/src/stateless/test.rs

This replaces https://github.com/githedgehog/dataplane/pull/671
THere is one extra simplification that we may want to add.

Simplify vtep config

---

stats/src/rate.rs

Fix typo in Derivative for SavitzkyGolayFilter.

fix: calculate bytes with weighted_sum_bytes

---

Cargo.lock
Cargo.toml
dataplane/Cargo.toml
dataplane/src/args.rs
dataplane/src/drivers/kernel.rs
dataplane/src/main.rs

Workers are spinned up by driver startup, using pipeline
fabric to create separate workflow for each thread. TX and RX
done by master thread.

feat: multithreading kernel driver

---

.config/nextest.toml
.github/workflows/dev.yml
Cargo.lock
Cargo.toml
dataplane/src/main.rs

pulls in changes which should make the vm test runner much more reliable

fix: vm test runner

---

.envrc
.gitignore
shell.nix

This is a short list of (harmeless) updates which make it easier to develop on this repo if you use NixOS

nixos tricks
