.github/workflows/dev.yml, .github/workflows/docs.yml, .github/workflows/lint-cargo-fmt.yml, .github/workflows/mergeability.yml, .github/workflows/sterile.yml
**Fix for working with merge queues.**
We do not want to publish a new version of the documentation when running CI checks in a merge queue. Let's skip the relevant steps.
Let's also specify the event type for merge groups. As per GitHub's documentation:
Although only the checks_requested activity type is supported,
specifying the activity type will keep your workflow specific if
more activity types are added in the future.
Note: Looking more specifically at the docs workflow, I think we could improve the workflow regarding whether or not to publish. In particular, we could have another bool parameter for the `workflow_dispatch`, because we don't necessarily want to publish a new version when running it. I think that ideally, we should split the `build` workflow for docs into `build`, …
=> ci: For merge groups, add event type, skip publishing docs

.github/workflows/bump.yml, .github/workflows/dev.yml, .github/workflows/sterile.yml
The bump.yml workflow, running on a schedule, has [always failed to complete so far][0]. This is because an "apt-get" command is missing the "install" subcommand, resulting in apt trying to interpret the name of the package we want to install as a subcommand, making the workflow fail.
Fix the command, to hopefully make the workflow succeed.
[0]: https://github.com/githedgehog/dataplane/actions/workflows/bump.yml
=> ci: Fix apt-get command in bump.yml, restore workflow summaries

justfile
The justfile would use a command snippet starting with `set -x` to determine the path of the Docker socket: this helps for debugging, but most of the time it only prints cryptic messages to the console each time we run `just`.
Make just print the output only when we set `debug=true`. We cannot use a variable in the triple-backquoted string, so we need a level of indirection with a separate command and a call to `shell()`.
=> justfile: Hide DOCKER_SOCKET command output

.github/workflows/docs.yml
Operator precedence matters... `!github.event_name == 'merge_group'` is likely different from `github.event_name != 'merge_group'`, and the condition to run the publish Action would fail to validate even on `push` events. Let's fix.
Fixes: #99
=> ci: Fix step condition, to fix docs publishing

.github/workflows/bump.yml
/home/runner/work/_temp/7e997195-83d5-48ad-a437-f4358b8c7ac6.sh: line 1: ./scripts/update-versions.sh: No such file or directory
I believe we need to call bump.sh instead.
Fixes: https://github.com/githedgehog/dataplane/issues/142
=> ci: Fix bump.yml by calling the right script

.github/workflows/sterile.yml, justfile
I don't remember for sure, but looking at the code, it seems to me that we no longer use (or build) the `dev-env` container, we just use the `compile-env` container nowadays?
If that's the case, we may want to merge this Pr, that removes references to `dev-env` in the repo's `justfile`. If indeed we no longer need this container, we should also remove the generated images from ghcr.io.
=> [RFC] justfile: Remove references to dev-env container

README.md
`rust-analyzer` will run `cargo` (and thus `rustc`, etc.) from `PATH`. But, `dataplane/compile-env` has its own `cargo` and `rustc` which causes issues. The fix is to tell `rust-analyzer` to use `cargo` from `dataplane/compile-env`.
=> README.md: Add VS Code setup instructions for rust-analyzer

.gitignore
This directory is generated when packaging the dataplane executable as a container. Tell Git to ignore it.
=> .gitignore: Add artifact directory

dpdk/src/dev.rs, errno/src/lib.rs
This was an ill-considered idea which saved me typing in exchange for making the DPDK error handling more complex.  Back it out and just use the full space of error codes.
=> Remove NegStandard from errno

.gitignore
We can have several artifacts, but the directory name is singular. Fix.
:facepalm:
=> .gitignore: Fix ignore pattern for artifacts

Cargo.lock, dpdk-sys/Cargo.toml
This makes the build a bit faster and versions a little easier to track.
=> Use workspace feature rather than individual versions

dataplane/src/main.rs
The copyright header crediting the project's authors was removed by mistake in a previous commit. Let's restore it.
Fixes: f07d50c4a75a ("Very basic dataplane")
=> dp: Restore copyright header

Cargo.lock, net/src/tcp/port.rs, net/src/udp/port.rs
On 2025-02-20, the rust team expects to [release version 1.85.0 of the compiler](https://releases.rs/docs/1.85.0/).
As with all releases, 1.85.0 brings new features and such.
However, 1.85.0 is slightly unusual in that it will be the first release wherein the 2024 _edition_ of rust will be considered stable.
Edition updates are intended to be released [on a three-year cadence](https://rust-lang.github.io/rfcs/3501-edition-2024.html#edition-cadence:~:text=Editions%20are%20intended%20to%20be%20released%20on%20a%20three%2Dyear%20cadence)
So we don't need to do this often.
_But_, we should do it promptly and properly when these dates come around.
For those unfamiliar with the edition system, have a look at
1. _[What are Editions](https://doc.rust-lang.org/edition-guide/editions/)_
2. …
=> Prep for 2024 edition

net/src/eth/mod.rs, net/src/icmp4/mod.rs, net/src/icmp6/mod.rs, net/src/ip/mod.rs, net/src/ip_auth/mod.rs, net/src/ipv6/mod.rs, net/src/tcp/mod.rs, net/src/udp/mod.rs, net/src/vlan/mod.rs
Feedback is that `inner` is a confusing name for these fields. `inner` was chosen on the grounds that there is an outer and an inner type (i.e. a transparent wrapper type which qualifies the wrapped inner type).
Still, if `.0` is easier for folks to think about then I won't argue.
This should have been done as part of commit 695633370144fd1e9d766974808217cf0a4b8942 (see https://github.com/githedgehog/dataplane/commit/695633370144fd1e9d766974808217cf0a4b8942) but I did not think about it at the time
=> Adjust "inner" naming convention to tuple struct convention

README.md, net/src/ipv4/mod.rs, net/src/ipv6/mod.rs, net/src/packet.rs
* Adds instructions for setting up `clippy` with `rust-anlayzer` in vscode.
* Makes header fields in parsed packets public for use outside the `net` crate
* Makes ip source addresses unicast by type, checked when parsed/set
=> Make header fields public, make ip headers unicast by type

.github/workflows/dev.yml, .github/workflows/lint-cargo-fmt.yml, .github/workflows/sterile.yml, dataplane/src/nat.rs, net/src/eth/ethertype.rs, net/src/eth/mod.rs, net/src/icmp4/mod.rs, net/src/icmp6/mod.rs, net/src/ip/mod.rs, net/src/ipv4/mod.rs, net/src/ipv6/addr.rs, net/src/ipv6/mod.rs, net/src/packet.rs, net/src/parse.rs, net/src/tcp/mod.rs, net/src/udp/mod.rs, net/src/vlan/mod.rs, net/src/vxlan/mod.rs
1. run clippy (it is honestly embarrassing that I forgot this before)
2. build the docs (equally embarrassing)
3. tame nightly clippy
4. tame nightly doc lints (we had a number of broken links)
5. make nightly build optional again
I know that testing your own CI is always convoluted and meta, but I do think [a quick fault injection test](https://github.com/githedgehog/dataplane/pull/218/commits/a4eef004ba724f4bf62b9619235bd6ae4a306d7a) is in order here.  Thus I bid thee, [behold my works](https://github.com/githedgehog/dataplane/actions/runs/13193895912)
I cooked a mock PR on top of this PR to illustrate that injecting a fault into the nightly (and only into the nightly) will cause us to pass CI but still generate [an admonition that nightly is …
=> Run clippy in CI (plus some CI cleanup)

README.md
Apparently, `RUSTC` is needed as well so that `rust-analyzer` doesn't use the system one instead of the sysroot one.
=> README.md: Add RUSTC var to vscode setup

.github/workflows/dev.yml, .github/workflows/docs.yml, .github/workflows/lint-cargo-fmt.yml, .github/workflows/sterile.yml
Adding two Pull Requests to the merge queue recently, we noticed that the workflows for the first one were cancelled:
Canceling since a higher priority waiting request for 'dev.yml:'
exists
([Reference](https://github.com/githedgehog/dataplane/actions/runs/13305862243/job/37156589226))
Let's adjust the concurrency group name to account for the different runs in the merge queue, and avoid having one Pull Request cancelling the others.
=> ci: Fix concurrency group for merge queue

.github/workflows/lint-license-headers.yml
Let's automate the check on SPDX header and copyright notice for new files. This commit introduces a workflow to ensure that all source code files have these headers. It's simpler to rely on the check than to expect reviewers to think about it each time a new file is added to the repository.
"Source code files" are currently defined as Rust files (.rs), shell scripts (.sh), and justfile.
We could optimize this workflow to run only when source files are modified. But the check is to trivial that it's currently not worth the pain.
=> Add CI check for SPDX/copyright headers

Cargo.lock, dataplane/Cargo.toml, dataplane/src/config.rs, dataplane/src/main.rs, dataplane/src/pipeline.rs, net/src/eth/mac.rs, net/src/packet.rs
This PR is here as a draft for discussion and refinement, when ready we can merge.
This PR:
* Adds a `Pipeline` object and `PipelineStage` trait to build a packet processing pipeline
* Adds a dummy Config object to use in the `PipelineStage` trait.
This this PR does *not* do:
* Implement a proper thread-safe config interface
* Fully implement the MetaPacket interface - we need to develop this based on stage needs
* As part of this, we need to figure out how to represent the selected output interface/encap/etc.
* Does not deal with any async interface to pause processing a packet and wakeup stages later
=> Add a pipeline interface to chain together processing stages

net/src/eth/mod.rs
Trivial bug which honestly should have been caught by tests a while back :shrug:
Looks like I need to write more tests for our get/set methods.
=> Fix copy-pasta in eth/mod.rs

net/src/eth/mac.rs
No need to write these methods twice.
=> Improve code-reuse in mac validation logic

Cargo.lock, Cargo.toml, deny.toml, routing/Cargo.toml, routing/src/adjacency.rs, routing/src/cpi.rs, routing/src/cpi_process.rs, routing/src/display.rs, routing/src/encapsulation.rs, routing/src/errors.rs, routing/src/interface.rs, routing/src/lib.rs, routing/src/nexthop.rs, routing/src/prefix.rs, routing/src/pretty_utils.rs, routing/src/rmac.rs, routing/src/routingdb.rs, routing/src/rpc_adapt.rs, routing/src/vrf.rs
This is super WIP and lacks the routing part (coming soon).
Opening this PR to get early feedback as suggested by @mvachhar and because there's some overlap with the work of the interface manager w.r.t modeling interfaces and neigh cache. @daniel-noland let's go over this at some point.
I'll be massively squashing fixes....
This is ready for review now. There's a lot of stuff to be done, but it's a starting point.
=> Definitions for types and entities in the routing module, and first implementation of the control-plane interface

net/src/ipv6/mod.rs
We were just using the wrong constant.
=> Incorrect ethertype in ICMPv6 parse

Cargo.toml, dataplane/src/nat.rs
- **nat: Remove tracing_test**
- **workspace: Add dataplane to default members**
Refer to individual commit logs for details.
=> Fix dataplane tests and re-add package to default workspace members

net/src/ip/mod.rs, net/src/ipv4/mod.rs, net/src/ipv6/mod.rs
This allows us to generate "interesting" IPv4/IPv6 packets more easily
=> Focused fuzzers for Ipv4/6

net/src/eth/mod.rs, net/src/icmp4/mod.rs, net/src/icmp6/mod.rs, net/src/ip_auth/mod.rs, net/src/ipv4/mod.rs, net/src/ipv6/mod.rs, net/src/packet.rs, net/src/parse.rs, net/src/tcp/mod.rs, net/src/udp/mod.rs, net/src/vlan/mod.rs, net/src/vxlan/mod.rs
DPDK uses `u16` where etherparse uses `usize`.
Both answers are reasonable in the context of packet processing. That said, we need to be compatible with both of them.
The only practical answer is to switch the parse traits to use `u16`.
Any alternative requires constant downcast checks throughout the rest of the code base.
=> Use `u16` as our size type in the parse traits

.github/workflows/lint-commitlint.yml
We have decided to enforce a structured formatting for the commit subject and description in the repository, namely the [Conventional Commit specification][0]. Add a CI workflow to make sure that new commits in Pull Requests abide by the specification.
I first tried to use https://github.com/wagoid/commitlint-github-action, which pulls by default the rules from [`@commitlint/config-conventional`][1], but I found them too restrictive. In particular, it enforces additional requirements on case that are not in the spec; worse, it unconditionally enforces maximum line lengths on subject, body and footer length. While I'm all in for restricting the subject's length, and generally wrapping the commit description, this makes it impossible to paste long links in the body or footer, or a large …
=> ci: Add linter for making sure we follow the  Conventional Commits spec

.github/workflows/lint-license-headers.yml
Just like commit 5cbff3518fef ("ci: Fix concurrency group for merge queue"), but for lint-license-headers.yml that for some reason doesn't have the updated concurrency group format.
=> ci: Fix concurrency group for license/headers check workflow

.gitignore, dataplane/src/main.rs, dataplane/src/packet.rs, dataplane/src/pipeline.rs, net/src/eth/mod.rs, net/src/headers.rs, net/src/ipv6/mod.rs, net/src/udp/mod.rs
Add back some of the changes that didn't make it from #233
* Adds abstraction for ethparse headers in net so that we can later enforce correct manipulations
* Add tests for full header parsing
* Add `Packet` to dataplane and drop `MetaPacket`
* `Packet` manages its own Mbuf and abstracts the buffer type for testing
These changes are a prelude to a better Pipeline interface that can actually be tested and works with different Iterator types.  That PR is still WIP, but close.
=> Add abstraction for header manipulation and Packet structure for dataplane

.github/workflows/lint-commitlint.yml
Fix a typo in the commit description, spotted by Sergei; also remove the use of the verbose output for the commitlint GitHub action, it is too verbose but brings no additional value on errors.
=> ci: Fix typo, remove verbose mode in commitlint linter workflow

dpdk/src/mem.rs
Trivial swap, but it is better to use the non `_w` vesions of dpdk-sys functions as they include doxygen -> rustdoc docs.
=> Use documented version of free

.github/workflows/bump.yml
The automated commit doesn't pass CI anymore now that we are using a more refined commit message format.
This commit fixes that.
=> build: fix incorrect commit message in bump.yml

.cargo/config.toml
These were part of an experiment which I shouldn't have ever checked in. They don't work, and wouldn't do anything useful even if they did work as intended.
=> fix: remove unused cargo alias commands

.github/workflows/dev.yml, .github/workflows/sterile.yml, README.md, design-docs/src/mdbook/src/build/compile-env.md, design-docs/src/mdbook/src/build/fake-nix.md, design-docs/src/mdbook/src/build/index.md
With the loss of [nix magic cache](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/) we have to use a much worse cache option for dpdk-sys, which has required us to (at least for the moment) remove musl support (see https://github.com/githedgehog/dpdk-sys/pull/92/commits/59661ba91c2d31f02c51cfeec02954a1fe01fdd6).
This commit removes musl from the CI and docs.
Hopefully this change can be reverted at some point because the sysroot is truly harder to debug without musl.
> [!NOTE]
> ~~Don't merge this until https://github.com/githedgehog/dpdk-sys/pull/92 lands and we update the dpdk-sys.env file to match~~
> It occurs to me that we can just merge the dpdk-sys.env update as a different PR.  All that will mean is that we don't build musl for the moment (even if it is shipped …
=> Remove musl support

.github/dependabot.yml
Mostly this should help keep our GitHub actions up to date.
I think this config is correct but it is hard to say because testing dependabot before merge is non trivial it seems.
=> Minor improvements to dependabot

.github/dependabot.yml
Dependabot uses "dep" as commit type, but the linter we have currently enforces the use of one of:
build, ci, docs, feat, fix, perf, refactor, style, test, chore,
revert, bump
We could change the linter, but for now let's simply change the commit type to "bump", which sounds accurate.
=> bump: Fix Dependabot's commits title message

Cargo.lock
Dependabot currently is running rust 1.84 so it can't bump our lockfile for us (due to edition change).
Running manually till they update it.
=> bump(cargo): manual bump

.github/workflows/lint-just-fmt.yml, .github/workflows/lint-validate-dependabot.yml
Based on the recent nonsense PR sequence trying to update dependabot.yml, it seems reasonable to include this.
=> fix (and lint) dependabot.yml

.github/workflows/dev.yml, justfile
- **build: Dismiss warning on detached HEAD check-out in "just build-sweep"**
- **build: Exit on error (-o pipefail) for "just build-sweep"**
- **ci: Fix "just build-sweep" step in dev workflow**
=> CI: Fix "just build-sweep" step

.github/workflows/lint-commitlint.yml, dpdk/src/queue/rx.rs, net/src/eth/mac.rs, net/src/vxlan/vni.rs
- **ci: List acceptable commit types in commitlint's workflow file**
- **chore: Suppress Nightly's warnings on #[must_use]**
First commit is not related - just a comment addition in the commitlint workflow file.
=> Clean up Rust Nightly warnings

.github/workflows/dev.yml
The step fails, presumably because of a compiler bug. As a result, all new Pull Requests get messages telling that the workflow has failed. This brings no useful info. If the step is broken for Nightly, let's as well disable it for now.
Link: https://github.com/githedgehog/dataplane/issues/309
=> ci: Disable "cargo clippy" with Nightly toolchain in dev workflow

dataplane/src/pipeline/dyn_nf.rs, net/src/buffer/mod.rs
Make it so that `DynNetworkFunction` implements `Any`.  The only constraint is that `DynNetworkFunction` has to be bound by `'static` and for that to happen, `PacketBufferMut` should be `'static`.  
The one change here is that any `NetworkFunction` that is to be put into a `DynPipeline` also has to be bound by `'static`.  That was the case anyway in the public API, but it is now true internally as well.
This PR is a precursor for some methods on `DynPipeline` that will allow pipeline stage lookup and downcast back to a concrete pipeline stage, though we need to do some other things for that to work, in particular, move to Rust 1.86 beta until April when 1.86 should be released.
Non-`'static` `NetworkFunction`s can still be statically chained.
=> Make `DynNetworkFunction` derive `Any`

rust-toolchain.toml
This will help IDEs while we are on the beta.
=> fix: add rust-toolchain.toml

Cargo.lock, Cargo.toml
~~Pipeline will fail while https://github.com/githedgehog/dplane-rpc/pull/25 is not merged~~
Pipeline should work now since referred to merged version 1.0.0.
=> Use version instead of branch for dplane-rpc

dataplane/src/nat/iplist.rs, dataplane/src/nat/mod.rs, dataplane/src/nat/prefixtrie.rs
Add rustdoc for most of nat's submodules, but not for the fabric.rs submodule, which is expected to change or disappear soon.
Note: The dataplane package is currently a binary, not a library, and its modules are private. As such, the doctest examples are not run on "cargo test", and the docs are not "expected" by rustdoc (so adding directive `#![deny(missing_docs)]` would have no effect).
=> doc(nat): Add some docs (rustdoc, comments) to the nat module

.github/workflows/dev.yml, .github/workflows/sterile.yml, dataplane/src/nat/fabric.rs, dataplane/src/nat/iplist.rs, dataplane/src/nat/mod.rs
- **fix(nat): Fix Clippy reports in tests**
- **ci(clippy): Run Clippy on all targets**
Can you believe it? Our CI doesn't run Clippy on all targets, and allowed Clippy reports to creep in via the unit tests!
Fix the issues in NAT tests. Then, make sure we run Clippy on all targets. While at it, let's also tell it to use all features and to fail on warnings.
=> Fix Clippy reports for NAT tests

.github/workflows/sterile.yml, Cargo.lock
To avoid contributors forgetting to commit the Cargo.lock updates, let's add a step to the sterile.yml workflow, to check whether building or testing the changes resulted in an updated Cargo.lock file. To do that, we check the result value from `git diff --quiet`.
=> ci: Check Git repository status to avoid omitting Cargo.lock updates

Cargo.lock, dataplane/Cargo.toml, dataplane/src/main.rs, dataplane/src/nat/mod.rs, dataplane/src/pipeline/dyn_nf.rs, dataplane/src/pipeline/pipeline.rs, dataplane/src/pipeline/sample_nfs.rs, dataplane/src/pipeline/static_nf.rs, dataplane/src/pipeline/test_utils.rs, net/Cargo.toml, net/src/lib.rs, net/src/packet/hash.rs, net/src/packet/meta.rs, net/src/packet/mod.rs
`Packet` (et. al.) need to live in net to avoid circular dependencies with, for example, the routing crate.
This logic was created in dataplane but never truly belonged there in the first place.
=> fix: Move Packet to net

justfile
Add a `just clippy` target to the justfile to help run Clippy. Running Clippy on the codebase is easy: `cargo clippy` should do. However, this may not run Clippy the way one should expect:
- If run without `just`, this may not pass all required flags to cargo, and may result Clippy running with different options. One consequence would be some undesired updates to the Cargo.lock file, or some Clippy reports that don't show as expected.
- By default, `cargo clippy` or even `just cargo clippy` will not run Clippy for all features, and in particular, they will not run on unit tests. This may hide Clippy reports.
In CI, we already make sure we run Clippy on tests since commit 550c75136cf9 ("ci(clippy): Run Clippy on all targets"). This commit adds a `clippy` target to the justfile to help …
=> build: Add "just clippy" target

net/src/packet/mod.rs, net/src/packet/utils.rs
Adds several getters for packet fields frequently retrieved, using in the results generalized types like std::net::IpAddr or Mac, (instead of DestinationMac or SourceMac) so that consumers need not depend on or distinguish those types. The methods are meant for code reuse, readability and ergonomics.
=> Packet utils

.github/workflows/dev.yml
We don't use the "stable" toolchain these days, given that we require Rust features that are in 1.86 (the current beta). Running the stable workflow in CI just burns resources and generates some noise in the discussion thread for the Pull Requests. Disable it.
This commit should be revert right before we revert commit 643de7afc7fc ("fix(justfile): Use beta release of rust, not stable").
Note: 1.86 is due to become stable on 3rd April (https://releases.rs/docs/1.86.0/).
=> ci: Disable stable toolchain for dev workflow

dpdk-sys/Cargo.toml, dpdk/Cargo.toml, id/Cargo.toml, net/Cargo.toml, routing/Cargo.toml
To avoid ambiguity in terms of licensing, explicitly provide a license parameters in the Cargo.toml of all packages in the repository. This should also help FOSSA, which currently struggles to determine the license for these crates.
The license is set to Apache-2.0, as for the packages that already stated a license.
Relates to #332
=> chore: Add missing license info in Cargo.toml files

dataplane/src/nat/iplist.rs, dataplane/src/nat/mod.rs
The previous design for mapping addresses for stateless NAT had an issue. By using a representation of a flattened list of all endpoints/public-IP prefixes, and only ensuring that the origin and target address lists are of the same size, we risk mapping regular unicast addresses to potential network or broadcast addresses of a subnet, if the subnet structure is different in the two sets.
This PR addreses the issue by making sure we simply translate from one prefix to a prefix of the same size. It also extend the revamped IpList struct to support exclusion prefixes as defined in the current API proposal for the Gateway.
=> Fix address mapping for stateless NAT

Cargo.toml, dataplane/Cargo.toml
The command line was throwing an error when requesting --help Enabling the default features at the top level Cargo.toml seems to fix the problem.
=> chore(dataplane): fix command line

Cargo.lock, Cargo.toml, dataplane/Cargo.toml, dataplane/src/main.rs, dataplane/src/nat/mod.rs, net/src/buffer/mod.rs, pipeline/Cargo.toml, pipeline/src/dyn_nf.rs, pipeline/src/lib.rs, pipeline/src/pipeline.rs, pipeline/src/sample_nfs.rs, pipeline/src/static_nf.rs, pipeline/src/test_utils.rs
This is needed to avoid circular dependencies.
=> Move the pipeline code to separate crate

justfile
- **build(justfile): Warn user when compile-env image is missing/outdated**
- **build(justfile): Add target to prune old compile-env image**
I know the check is barely readable; I decline all responsibility for `just --fmt`'s output.
=> justfile: Add compile-env images handling facilities

clippy.toml, net/src/eth/mod.rs, net/src/headers.rs, net/src/ipv4/mod.rs, net/src/ipv6/mod.rs, net/src/packet/hash.rs, net/src/tcp/mod.rs, net/src/udp/mod.rs, net/src/vlan/mod.rs, net/src/vxlan/mod.rs, net/src/vxlan/vni.rs, pipeline/src/lib.rs, pipeline/src/pipeline.rs, pipeline/src/sample_nfs.rs, pipeline/src/static_nf.rs, pipeline/src/test_utils.rs
Instead of manually allowing unwrap(), expect(), and panics in every test module, introduce a clippy.toml file at the root of the repository, using the relevant configuration options to allow these functions inside of test modules.
With this configuration file, most macros are now unnecessary; clean them up.
=> style: Add clippy.toml to allow unwrap(), expect(), panics in tests

.github/workflows/dev.yml, dpdk/src/mem.rs
- **style(dpdk): Fix Clippy report about raw pointers comparison**
- **Revert "ci: Disable "cargo clippy" with Nightly toolchain in dev workflow"**
It looks like whatever compiler bug affected us before has been solved, we can use Clippy with the nightly toolchain again.
=> Re-enable Clippy with the nightly toolchain

.github/workflows/dev.yml
The summary step fails to detect failures at the Clippy or "build-each-commit" steps, because it's not looking for the conditions of these steps at the end of the run. Update the condition to ensure that we look at these results.
=> ci: Fix summary step for dev workflow

Cargo.lock, Cargo.toml, net/Cargo.toml, net/src/headers.rs, net/src/packet/display.rs, net/src/packet/test_utils.rs
It turns out that (upcoming) vxlan encap / decap benefit from making eth an optional field.
Specifically, at one point in the pipeline we simply don't know the ethernet header we want to use yet.
It is also entirely possible that we will use layer 3 tunneling for other protocols in the future so making eth required is not generally wise.
=> Make eth optional

dataplane/src/main.rs, pipeline/src/sample_nfs.rs
rides on https://github.com/githedgehog/dataplane/pull/363
A pipeline may be built to contain more than a packet dumper; e.g. one right after some ingress stage and another one right before egress. In order to know at which stage a packet was dumped, let PacketDumper objects get a name that is displayed along with the packet dump.
=> Let PacketDumpers have a name

Cargo.lock, Cargo.toml, net/Cargo.toml, net/src/eth/mac.rs, net/src/packet/display.rs
=> Remove nom dependency

Cargo.lock, dataplane/src/drivers/dpdk.rs, dataplane/src/drivers/kernel.rs, net/Cargo.toml, net/src/buffer/mod.rs, net/src/buffer/test_buffer.rs, net/src/headers.rs, net/src/ipv6/mod.rs, net/src/lib.rs, net/src/packet/display.rs, net/src/packet/hash.rs, net/src/packet/meta.rs, net/src/packet/mod.rs, net/src/packet/test_utils.rs, net/src/udp/mod.rs, net/src/vxlan/encap.rs, net/src/vxlan/mod.rs, net/src/vxlan/vni.rs, pipeline/Cargo.toml, pipeline/src/lib.rs
> [!NOTE]
> ~~This is now on rebased top of #383 which should go in first~~ mission complete
This patch series is aimed at two major goals
1. implement vxlan encap / decap
2. unify the packet and pipeline and net functionality to the point where we can implement the next set of tasks (i.e. interface manager and routing crates)
=> vxlan encap / decap

README.md
We need Rust 1.86+ for running the dataplane. We switched to the beta toolchain for some time because of this requirement. Let's fix the warning in the README.md.
=> docs(README.md): Fix Rust version requirement

dataplane/Cargo.toml, net/Cargo.toml, net/src/eth/ethtype.rs, net/src/eth/mac.rs, net/src/interface/mod.rs, net/src/ipv4/addr.rs, net/src/ipv6/flow_label.rs, net/src/tcp/checksum.rs, net/src/tcp/port.rs, net/src/udp/checksum.rs, net/src/udp/port.rs, net/src/vlan/mod.rs, net/src/vxlan/mod.rs, net/src/vxlan/vni.rs
I originally had dreams of making the net crate fully support no-std and limited resource environments. As a result, I made things optional which, in retrospect, have no need to be. Serde is one of those things.
So here ya go, with appologies to @qmonnet who just fixed this feature I'm removing.
=> fix(net): serde should not be optional

mgmt/src/rpc/overlay/display.rs, mgmt/src/rpc/overlay/mod.rs, mgmt/src/rpc/overlay/tests.rs, mgmt/src/rpc/overlay/vpc.rs, mgmt/src/rpc/overlay/vpcpeering.rs, routing/src/lib.rs, routing/src/pretty_utils.rs
on https://github.com/githedgehog/dataplane/pull/391
Implements Display for Overlay config.
**Sample:** Vpc table summary showing what vpcs peer with each other
```
─────────────────────────────────── VPCs (4)  ───────────────────────────────────
VPC                VNI      peers     remote             peering name      
VPC-1              3000     3         VPC-2              VPC-1--VPC-2      
VPC-3              VPC-1--VPC-3      
VPC-4              VPC-1--VPC-4      
VPC-2              4000     2         VPC-1              VPC-1--VPC-2      
VPC-3              VPC-2--VPC-3      
VPC-3              2000     2         VPC-1              VPC-1--VPC-3      
VPC-2              VPC-2--VPC-3      
VPC-4              6000     1         VPC-1              VPC-1--VPC-4      
```
**Sample**: full …
=> Dataplane configuration display

.config/nextest.toml
nextest is a more modern test runner / reporting tool than the one which ships with cargo. nextest is significantly faster than cargo test and can report as junit et al.
To run nextest tests you can call
```
just cargo nextest run
```
It was used before, but I removed it in the name of making the justfile less complex.
Since then the justfile has been refactored to the point where nextest is very low cost to support, so we may as well add it back.  I like the faster tests.
Note: we can't currently support nextest in the sterile build env as I have yet to add it to the compile-env.  I may do this later if folks want it.
=> feat: add back nextest config

Cargo.lock, Cargo.toml, dataplane/Cargo.toml, dataplane/src/drivers/kernel.rs, interface-manager/Cargo.toml, interface-manager/src/interface/association.rs, interface-manager/src/interface/bridge.rs, interface-manager/src/interface/mod.rs, interface-manager/src/interface/properties.rs, interface-manager/src/interface/vrf.rs, interface-manager/src/interface/vtep.rs, interface-manager/src/lib.rs, interface-manager/src/netns.rs, net/Cargo.toml, net/src/interface/mod.rs, rekon/Cargo.toml, rekon/README.md, rekon/src/lib.rs, scripts/test-runner.sh, vpc-manager/Cargo.toml, vpc-manager/src/lib.rs, vpc-manager/tests/reconcile.rs
Cleanup finally finished.
Don't merge until #419 lands
=> Interface-manager part 2

.github/workflows/dev.yml
I don't like the comments generated by the CI workflow when the job with the Nightly toolchain fails, I find them disruptive when trying to follow a conversation on a GitHub Pull Request page. Plus given that the job is optional, we barely ever click the links from the comments anyway. A failed status check draws more attention to the actual issue, in my opinion.
Motivation:
- My objective here is to remove the creation of the comments when an optional step fails
- To get some feedback on failure instead, we remove the `continue-on-error` directives: I expect this to make the job using the Nightly toolchain fail on errors (which should show up in the list of status checks at the bottom of the page).
Will a job failure block the CI or the merge queue?
- The individual jobs for the dev.yml …
=> CI: Remove comments on Nightly job failures

dataplane/src/drivers/kernel.rs, net/src/packet/display.rs
Implement Display for invalid packet as the Debug display is hard to read. This also fixes the kernel driver log.
**Sample output:**
```
2025-05-07T17:34:22.727791Z ERROR main ThreadId(01) dataplane::drivers::kernel: 220: Failed to parse packet!!:
Invalid packet
────────────────────────────────────────────────────────────────────────────────────────────────────
[0000-0031] 00 00 00 00 00 00 00 00 00 00 00 00 86 dd 60 0e 50 ad 00 20 06 40 00 00 00 00 00 00 00 00 00 00 
[0032-0063] 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 9c ae c3 83 25 72 9a 53 50 53 
[0064-0085] c5 e8 80 10 02 00 00 28 00 00 01 01 08 0a c5 13 21 2e c5 13 21 01 
────────────────────────────────────────────────────────────────────────────────────────────────────
buffer: 86 data octets (headroom: 96 …
```
=> Implement Display for Invalid Packet

.github/dependabot.yml
Updates for gateway_config require manual adjustments in our code for now, we need someone to take care of them. Attempts from the bot to autmatically bump the version number (or commit SHA) are unlikely to be correct, so let's discharge Dependabot of the task.
=> chore(dependabot): Make Dependabot ignore gateway_config updates

deny.toml
In CI, we run "cargo deny check" to check a number of things regarding licensing and dependencies. One of the checks consist in reporting duplicate versions of crates loaded as dependencies. So far, we've "denied" these, meaning we have been rejected changes that led to rely on multiple versions of a given crate.
The expected benefit is easier debugging (less confusion as to what code is actually running). This also comes with a number of drawbacks: it makes it harder to pull in new dependencies, or even to upgrade dependencies when not all dependencies are in sync regarding recursive dependencies versions.
We have spent too much time struggling around this. We need to pull the dependencies we want to use, we can't afford bumping versions for multiple projects, sometimes not reactive, …
=> ci(deny): Allow multiple crates versions

net/src/packet/hash.rs, scripts/test-runner.sh
The test runner that makes unit tests run inside of a Docker container tend to make it harder to run and debug tests. Only use the container for packages that do require specific configuration or elevated privileges, not for the other packages.
Code from Daniel.
=> test(test-runner): Per-package opt-in for test runner

Cargo.lock, Cargo.toml, interface-manager/Cargo.toml, interface-manager/src/netns.rs, net/src/ipv4/dscp.rs, net/src/ipv4/ecn.rs, net/src/ipv4/mod.rs
Cleanup required to make bump.sh work again
This can't land until #452 does.
The nix dup dependency can not be fixed without changing way too much code.
=> Fix bump.sh

mgmt/src/models/external/overlay/vpc.rs, mgmt/src/processor/confbuild.rs
When building the configuration of FRR, do not add an import route- map if the VPC has no peerings. In principle, it should not harm. However, such a route-map is useless and we speculate it may confuse frr-reload.
=> feat(mgmt): no import routemap in peeringless VPC

.github/workflows/bump.yml
Workflow bump.yml performs a dry run of the "cargo upgrade" command, and processes its output to determine the list of packages to upgrade (then upgrades them as individual commits). It expects the output to be a Markdown array, of this kind:
name     old req compatible latest new req
====     ======= ========== ====== =======
netdev   0.34.0  0.34.1     0.34.1 0.34.1
smallvec 1.14.0  1.15.0     1.15.0 1.15.0
However, the recent introduction of the dataplane CLI with a separate binary, and in particular, a set of dependency crates that are not managed from the toplevel Cargo.toml, caused "cargo upgrade" to process two files and to produce two different tables:
$ cargo upgrade --incompatible=allow --dry-run 2>/dev/null
name     old req compatible latest new req
====     ======= ========== …
=> ci: Fix generation of list of packages to update

.github/workflows/bump.yml
We have an issue in the bump.yml workflow. It fails to update recursive dependencies for the project when these dependencies are passed as links to Git repositories (for example, a branch name and an URL to a GitHub repository).
I'm not sure what happens exactly, but there seems to be an issue with the `cargo upgrade` command: it expects some local index to be populated when running the upgrade for the Git-based dependency, and calls `cargo update` under the hood with the `--offline` option, but this command fails.
We've opened a GitHub issue for the upstream `cargo-edit` project (providing `cargo upgrade`), but in the meantime, let's re-order the commands we run: if we do the `cargo update` first, this should populate whatever index `cargo upgrade` seems to rely on when we try to bump …
=> ci: Reorder steps in bump.yml workflow to fix upgrades from Git

.github/workflows/bump.yml
We recently adjusted our bump.yml workflow to account for upgrades in the CLI repository (cli), but forgot to "git add" the related Cargo.toml file, making the workflow fail when toplevel Cargo files are not modified (because there's nothing to commit - the change is in cli/Cargo.toml). Let's add it.
Fixes: e3522a0e664d (ci: Fix generation of list of packages to update)
=> ci: Fix bump.yml workflow for CLI

mgmt/src/grpc/converter.rs
Admit incomplete configurations that do not have underlay or overlay so that empty configs can be pushed to wipe out the system. Except for syntax, config validation should be moved out of the gRPC handlers.
=> Relax configuration constraints in gRPC

.github/workflows/bump.yml
This reverts commit f6198c0f26d7f239cc8be9086c2942ebc1c12834.
The workflow is broken when running on PRs, and I don't have the time to fix it. Remove the run on PRs for now, to avoid failing worfklows in CI when we update the file.
In other words, make bump not bump on bump bumps.
=> CI: Make bump not bump on bump bumps

Cargo.lock, Cargo.toml, mgmt/Cargo.toml, mgmt/src/processor/proc.rs
This all started with yet another breakage of the build.yml workflow. The workflow complained that bumping dependencies failed: it tried to bump the `hyper` crate from version 0.14 to 1.6, and failed, because version 1 of the crate introduced breaking changes. In particular, the `hyper::server` submodule is gone, meaning that we could no longer pull the `Accept` trait.
As it turns out, we do not need the Accept trait to be implemented for the UnixAcceptor to use it with the 'tonic' crate, we only need the `Stream` trait (which we have).
Refactor `poll_next()` and `poll_accept()`: given that the former would only wrap around the latter, inline the code from `poll_accept()` into `poll_next()`, and drop the implementation of the `Accept` trait.
After that, we can simply drop the direct …
=> Remove direct dependency on 'hyper' crate

mgmt/src/models/internal/routing/evpn.rs, mgmt/src/models/internal/routing/vrf.rs, mgmt/src/processor/confbuild.rs, mgmt/src/processor/tests.rs, mgmt/src/vpc_manager/mod.rs, net/src/ip/mod.rs, net/src/ipv4/addr.rs, net/src/ipv6/addr.rs
This PR sets the bridge (and vtep + vrf) MAC to a consistent value, as well as adding infrastructure to allow specifying the VTEP ip more logically.
Doing so requires a bit of plumbing, but not a lot of new logic.
=> Set bridge mac

.config/nextest.toml, .github/workflows/dev.yml, justfile, scripts/rust.env
CI tune up time!
This is all basically in service of making flaky tests (specifically flaky fuzz tests) visible in CI, while not punishing PRs which have nothing to do with that flake.
Finding new flakes is just part of fuzzing the codebase.
We should just create an issue to investigate and move on (assuming that the issue really isn't caused by the PR in question).
> [!NOTE]
> This PR does not address flakes in the sterile environment.  I'll get to that in a future PR.
See https://github.com/githedgehog/dataplane/pull/533 for examples of the types of messages this new functionality generates.
See also issue #446 for motivation
=> CI tune up (deal with flaky tests)

routing/src/prefix.rs
The trait was first implemented in commit 39abac4465e9. It was later removed in commit 4caec75ebb02, seemingly because the introduction of the `PrefixString` struct made it less relevant to build prefixes from strings. But it remains faster, and easier to read, to use the `"1.2.3.4/24".into()` notation to build numerous prefixes for unit tests, so let's re-add support for it.
Used in #445, #470, #529.
=> test(routing): Re-implement From<&str> trait for Prefix

net/src/eth/mac.rs, net/src/headers.rs
:rotating_light: **Required to fix current CI failures** on dev.yml with nightly toolchain
It seems that rustc is not able to tell we're using `MacTestStringGenerator` and `CommonHeaders` through the `.with_generator()` method. Let's tell it to ignore dead code for these structs.
Fixes: 613cf78ef5da ("feat(net): Add Mac::try_from::<&str>()")
Fixes: e1b81987d3b6 ("test(net): Add fuzz tests for parsing packet headers")
=> fix(net): Fix build warnings (dead_code false positives)

mgmt/src/models/external/mod.rs, mgmt/src/models/external/overlay/mod.rs, mgmt/src/models/external/overlay/tests.rs, mgmt/src/models/external/overlay/vpc.rs, mgmt/src/models/external/overlay/vpcpeering.rs
This Pull Request implements some validation for `VpcExpose`, `VpcManifest`, `VpcPeering`, and `VpcTable` objects received from the gRPC server.
Fixes: #442
Please refer to individual commit descriptions for details.
=> mgmt: Validate VpcPeering & friends

Cargo.lock, Cargo.toml, mgmt/Cargo.toml, mgmt/src/grpc/converter/mod.rs, mgmt/src/grpc/converter/old_impl.rs, mgmt/src/models/external/overlay/vpc.rs, mgmt/src/models/internal/routing/bgp.rs
This PR does the following:
1. It has fuzz testing now for the converter
2. It has bug fixes/extensions for the problems the fuzzer found
3. The converter implementation has been moved from a single file to a directory
4. Updates to gateway-proto 0.2.3
Left to do in future PRs
1.  Move implementation to separate files
2. Remove `convert_*` functions and just implement in the `TryFrom` interfaces
=> Fix bugs, extend tests, and refactor gRPC converter

Cargo.lock, Cargo.toml
Do not merge until [gateway-proto#29](https://github.com/githedgehog/gateway-proto/pull/29) is merged.
Now that dataplane uses Rust 1.87.0 we can use
gateway-proto 0.2.4 code that requires Rust 1.87.0
=> chore(mgmt): Bump gateway-proto to 0.2.4

mgmt/src/models/internal/mod.rs, mgmt/src/models/internal/nat/table_extend.rs, mgmt/src/models/internal/nat/tables.rs, mgmt/src/processor/confbuild.rs
Based on #470
- **feat(nat): Optimize peerings before adding them to NAT tables**
- **chore(nat): Derive Clone trait for NAT tables**
- **feat(nat): Hook NAT tables creation into internal config build**
Fixes: #472
=> NAT: Hook NAT table construction into `mgmt`

Cargo.lock, Cargo.toml, mgmt/src/grpc/converter/interface.rs
* Respect Vtep mac addresses from gRPC
* Make sure that interface mac addresses are valid unicast, non-zero, source macs
Fixes #581
=> Have gRPC conversion respect mac addresses for Vtep interfaces

codecov.yml
Comments in Pull Requests discussions from the Codecov bots are intrusive, in the sense that they break the flow of the conversation, and they also generate email notifications to all contributors subscribed to the Pull Request.
Let's disable the comments. The status check at the bottom of the Pull Requests are enough to get some signal about the change in coverage.
I wish there was a way to configure this in Codecov's online interface, or at least to hide the config file under `.github/` or as a dotfile, but it seems that none of these is possible :cry. The toplevel config file seems to be our only option.
Link: https://docs.codecov.com/docs/pull-request-comments#disable-comment
=> chore(codecov): Add Codecov config file to disable comments in PRs

Cargo.lock, Cargo.toml
gateway-proto cargo crate version was not synced with repo version. Now it is synced and the version is 0.9.0
=> chore: Sync version of gateway-proto to 0.9.0

mgmt/tests/reconcile.rs
The annotation was causing tests to fail on some machines
=> fix(mgmt): Remove unused reconcile_demo annotation

dataplane/src/args.rs, scripts/test-runner.sh
* Address all copilot comments from #601 
* Fix path bug in `test-runner.sh` so that `just cargo run -p dataplane` works as expected
* Fix help messages for cli arguments.
=> Miscellaneous CLI fixes for dataplane

dataplane/src/nat/mod.rs
Based on #598
Based on Fredi's recent work to add the VNI from the source VPC to packet metadata, here's an update to the NAT code to read the VNI from metadata (rather than the hardcoded placeholder that we had).
We also update unit tests accordingly.
=> feat(nat): Use actual source-VPC VNI with NAT

.config/nextest.toml
It appears that the cause of the flakiness was both reconcile tests running in threads in parallel.  Because they use threads the two tests ran in the same netns and could fight to configure the same interfaces causing failures.
The move to nextest for test running coincidentally makes parallel tests run in separate processes for runs and so now each process gets its own netns from the existing test fixture.
As a result, this test should no longer be flaky.  If flakiness reappears we should create a new issue and add it back to the overrides for multiple retries.
Fixes #446
=> test(mgmt): Remove the reconcile_* fuzz tests from flakes

Cargo.lock, Cargo.toml, dataplane/Cargo.toml, dataplane/src/nat/mod.rs, dataplane/src/nat/stateful/allocator.rs, dataplane/src/nat/stateful/mod.rs, dataplane/src/nat/stateful/sessions.rs, dataplane/src/nat/stateless.rs, net/src/headers.rs, net/src/ip/mod.rs, net/src/packet/mod.rs, net/src/tcp/mod.rs, net/src/tcp/port.rs
This PR contains various changes to the code for stateful NAT, leading to the (partial) implementation of a session manager based on dashmap.
Best reviewed per-commit.
Missing components:
- Create corresponding reverse sessions when we create new sessions
- Port/IP allocator (future work)
- Garbage collector to clean up stale sessions (future work)
Fixes: #181
=> Stateful NAT: Implement (most of) session manager

dataplane/src/packet_processor/ipforward.rs, net/src/headers.rs
* We were not computing IP header checksums when needed.
* We were wrongly computing it in case of vxlan
=> Fix Ip and UDP checksums

justfile
Following recent changes in dpdk-sys and in the dataplane repository, the container names now have a ".debug" or ".release" suffix. We forgot to update the compile-env check accordingly. There's no reason to re-create the full container path in the warning, by the way: let's just use `_compile_env_container` that contains the full string already.
=> build: Fix warning for compile-env presence check

mgmt/Cargo.toml, mgmt/src/models/internal/natconfig/test.rs, nat/Cargo.toml, nat/src/stateless/config/prefixtrie.rs, nat/src/stateless/config/tables.rs, nat/src/stateless/mod.rs, nat/src/stateless/test.rs
- **feat(nat): Implement PartialEq, Eq for NatTables (and related types)**
- **test(nat): Add stateless NAT test in "stateless" module**
- **test(mgmt): Remove redundant tests for stateless NAT**
Please take a look at individual commit descriptions for details.
=> NAT: Move tests back to "nat" crate

mgmt/src/frr/renderer/mod.rs
When trying to update to the latest dpdk-sys (I think with a Rust version upgrade?), we get a complaint from Clippy; let's address it.
(Link: https://github.com/githedgehog/dataplane/actions/runs/15975791652/job/45057799019?pr=647)
=> style(mgmt): Fix a Clippy report

Cargo.lock, mgmt/src/models/external/mod.rs, mgmt/src/models/external/overlay/tests.rs, mgmt/src/models/external/overlay/vpcpeering.rs, mgmt/src/models/internal/natconfig/table_extend.rs, nat/Cargo.toml, nat/src/stateless/config/tables.rs, nat/src/stateless/iplist.rs, nat/src/stateless/mod.rs, routing/Cargo.toml, routing/src/prefix.rs
- **fix(nat): Fix TrieValue building and address mapping**
- **feat(nat): Simplify struct TrieValue**
- **feat(nat): Add proper error handling for IpList (stateless NAT)**
- **fix(nat): Handle prefix size correctly**
- **test(nat): Add IPv6-based tests for IpList**
- **test(nat): Add bolero test for IpListSubset and offset checks**
- **test(routing): Add fuzzing test for PrefixSize**
- **fix(routing): Modify PrefixSize to improve mathematical soundness**
- **feat(mgmt): Simplify and optimise TrieValue generation**
The main motivation of this PR is to reduce the memory footpring and the complexity of the address mapping for stateless NAT, by reducing the amount of information stored in `struct TrieValue`.
Please refer to individual commit descriptions for details.
=> Stateless NAT: Simplify TrieValue, improve error handling in IpList, fix prefix size handling

nat/src/stateful/allocator.rs, nat/src/stateful/mod.rs, nat/src/stateful/sessions.rs
In commit b12d185a5e87 we changed the way we're handling directions in NAT stages. That commit mostly focused on stateful NAT, and the sensitive code portions in the module for stateful NAT were simply commented out, given that the code is not complete anyway.
Here we adjust the code for stateful NAT, on the same basis. We make it handle both source and destination NAT, in a single pipeline stage. This requires storing more information in the state tables, given that we need addresses and port for both directions.
=> fix(nat): Make stateful NAT code direction-independent

Cargo.lock, Cargo.toml, config/src/lib.rs, config/src/utils/collapse.rs, config/src/utils/mod.rs, dataplane/Cargo.toml, dataplane/src/main.rs, dataplane/src/packet_processor/mod.rs, lpm/src/trie/mod.rs, mgmt/Cargo.toml, mgmt/src/processor/confbuild/internal.rs, mgmt/src/processor/launch.rs, mgmt/src/processor/proc.rs, mgmt/src/tests/mgmt.rs, nat/src/stateless/mod.rs, nat/src/stateless/setup/mod.rs, nat/src/stateless/setup/range_builder.rs, nat/src/stateless/setup/tables.rs, nat/src/stateless/test.rs, net/src/ipv4/addr.rs, net/src/ipv6/addr.rs, net/src/packet/test_utils.rs, pkt-meta/Cargo.toml, pkt-meta/src/dst_vni_lookup/mod.rs, pkt-meta/src/dst_vni_lookup/setup.rs, pkt-meta/src/lib.rs
Currently the NAT stage does the dst VNI lookup and annotates the packet.
This removes that logic and adds a custom pipeline stage `DstVniLookup` that will lookup the dst VNI and drop the packet if not found, otherwise will annotate the packet with the dst VNI.
=> Add `dst_vni_lookup` pipeline stage

nat/src/stateless/mod.rs, nat/src/stateless/setup/mod.rs, nat/src/stateless/setup/tables.rs, nat/src/stateless/test.rs
Now that we can rely on a dedicated pipeline stage to perform the destination discriminant lookup (at the moment, destination VNI), we do not need to keep this indirection level in the NAT tables to find the rule (virtually) associated with the destination VNI for source NAT.
Instead of keeping the two lookups - first to find the index of the `NatPrefixRuleTable` in the `NatPeerRuleTable`, then to consult the `NatPrefixRuleTable` - simplify the structure of the NAT tables for source NAT, to only contain a per-destination-VNI hashmap containing the rules. This makes the NAT code simpler, in particular for building the rules tables.
=> Stateless NAT: use `dst_vni` packet metadata

Cargo.lock, Cargo.toml, interface-manager/Cargo.toml, interface-manager/src/interface/mod.rs, interface-manager/src/interface/tap.rs, net/src/buffer/mod.rs, net/src/interface/mod.rs
This is the first of a series of PRs which add the ability to inject traffic from our pipeline back into the linux kernel.
Each of the commits messages contain reasoning for why this change is needed.
The first commit, which changes the max lenght of InterfaceName is especially important in order to maintain our contract with linux when we create tap devices via ioctl.
=> Tap support phase 1

interface-manager/src/interface/tap.rs, mgmt/src/vpc_manager/mod.rs
* This is a quick fix
* Name tap device for interface `foo`  as ` foo-tap`. Otherwise creation fails as `foo` already exists.
=> Rename tap device

.github/workflows/bump.yml
Leave dpdk-sys updates to https://github.com/githedgehog/dpdk-sys/blob/main/.github/workflows/update-dp.yml, and run dependency updates weekly only.
=> CI: Run bump.yml weekly, drop dpdk-sys update from this repo

lpm/src/prefix/ip.rs, lpm/src/prefix/mod.rs
Define and implement two methods to the `IpPrefix` trait to return the size and the last address within a prefix range, respectively.
This is in preparation for the work for the IP/port allocator for stateful NAT.
=> Extend `IpPrefix` with `.size()`, `.last_address()`

nat/src/stateful/allocator.rs, nat/src/stateful/mod.rs, nat/src/stateful/natip.rs, nat/src/stateful/port.rs, nat/src/stateful/sessions.rs
Simply move some parts of the code, namely the `NatPort` struct and surrounding code, and the `NatIp` trait, to their own files, to make future updates to the stateful NAT code easier to follow.
=> Stateful NAT: Split to submodules in prep for allocator work

.github/workflows/dev.yml
Pass the profile argument for the current job to the "just" invocation at the "cargo deny check" step of CI runs. Without this argument, the step would default to the "debug" profile and would _always_ pull the debug compile-env image, even for jobs where all other steps use the "release" profile, adding a useless image pull. Now that we pass the argument, the step should use the same image as the rest of the job, either "debug" or "release" depending on which job matrix case we run.
Fixes: e0dc86f54151
=> fix(ci): Avoid pulling debug compile-env just for "cargo deny check"

routing/src/fib/fibgroupstore.rs
Building the Rust docs currently produces a warning:
$ just cargo doc
[...]
warning: unclosed HTML tag `FibGroup`
--> routing/src/fib/fibgroupstore.rs:16:60
|
16 | //! Any modification of the FibGroupStore or the Rc<RefCell<FibGroup>>s it contains
|                                                            ^^^^^^^^^^
|
= note: `#[warn(rustdoc::invalid_html_tags)]` on by default
help: try marking as source code
|
16 | //! Any modification of the FibGroupStore or the `Rc<RefCell<FibGroup>>`s it contains
|
Fix it.
=> fix(routing): Fix doc warning (missing source code marking)

.github/workflows/dev.yml, dataplane/src/main.rs, dataplane/src/packet_processor/ipforward.rs, dataplane/src/packet_processor/mod.rs, mgmt/src/processor/launch.rs, mgmt/src/processor/proc.rs, mgmt/src/tests/mgmt.rs, nat/src/stateful/mod.rs, nat/src/stateless/mod.rs, nat/src/stateless/test.rs, net/src/packet/display.rs, net/src/packet/meta.rs, pkt-meta/src/dst_vni_lookup/mod.rs, pkt-meta/src/dst_vpcd_lookup/mod.rs, pkt-meta/src/dst_vpcd_lookup/setup.rs, pkt-meta/src/lib.rs, stats/src/dpstats.rs, stats/src/rate.rs, vpcmap/src/lib.rs
This moves us to storing a VPC Discriminant in the packet meta data instead of a source and dest VNI.
It also moves `lookup_dst_vni` to `lookup_dst_vpcd` and makes it operate on discriminants instead of VNIs.
Fixes #808
Fixes #811
=> Move to using VPC discriminant in packet metadata

nat/src/stateful/apalloc/test_alloc.rs
- **test(nat): Move back comment to correct location**
- **test(nat): Remove useless "tests" module in test_alloc.rs**
Best reviewed by hiding whitespace changes.
=> NAT: allocator tests clean-up (v2)

Cargo.lock, Cargo.toml, net/src/udp/mod.rs, pkt-meta/Cargo.toml, pkt-meta/src/flow_table/README.md, pkt-meta/src/flow_table/atomic_instant.rs, pkt-meta/src/flow_table/flow_info.rs, pkt-meta/src/flow_table/flow_key.rs, pkt-meta/src/flow_table/mod.rs, pkt-meta/src/flow_table/table.rs, pkt-meta/src/flow_table/thread_local_pq.rs, pkt-meta/src/lib.rs
This PR adds the initial flow table data structure, but not the corresponding pipeline stages.
The appropriate pipeline stages will be added as part of NAT integration and the interface for the flow table updated for anything needed that was not anticipated here.
We also need a way to run the shuttle tests in CI, but that is beyond the scope of this PR.
Fixes #783
=> Initial flow table data structure

Cargo.lock, dataplane/src/main.rs, dataplane/src/packet_processor/mod.rs, mgmt/src/processor/launch.rs, mgmt/src/processor/proc.rs, mgmt/src/tests/mgmt.rs, nat/Cargo.toml, nat/src/lib.rs, nat/src/stateful/allocator.rs, nat/src/stateful/allocator_writer.rs, nat/src/stateful/apalloc/alloc.rs, nat/src/stateful/apalloc/mod.rs, nat/src/stateful/apalloc/setup.rs, nat/src/stateful/apalloc/test_alloc.rs, nat/src/stateful/mod.rs, nat/src/stateful/sessions.rs, nat/src/stateless/setup/mod.rs, pkt-meta/src/flow_table/table.rs
This PR contains a bunch of fixes for stateful NAT allocator's creation, and hooks the actual creation of the allocator to the config processing components in the `mgmt` crate.
Caveats:
- Only the initial creation of the allocator is supported at this time, not the update on subsequent configuration updates, yet
- The dataplane only supports configurations with the same numbers of original and target IPs for NAT. This is because of stateless NAT requirements, which are currently being enforced to stateful NAT, too (because the config for both modes is built unconditionally)
Relates to (but does not fully address) #790
=> Stateful NAT: Build allocator from config

dataplane/src/drivers/kernel.rs, dataplane/src/main.rs, dataplane/src/packet_processor/mod.rs, dpdk/src/mem.rs, nat/src/stateless/natrw.rs, net/src/buffer/mod.rs, pkt-meta/src/dst_vpcd_lookup/mod.rs, routing/src/atable/atablerw.rs, routing/src/fib/fibtable.rs, routing/src/interfaces/iftablerw.rs, routing/src/router.rs
Multi-threading requires use to be able to construct pipelines in each worker.  This makes the code that sets up the pipeline `Send` + `Sync` so that each thread can get a the setup function and create a pipeline.
This PR does *not* actually create the worker threads in the drivers.
=> Make pipeline construction `Send` + `Sync` for multi threading

.github/workflows/bump.yml
Avoid compiling cargo-binstall from GitHub workflow - the whole point of getting this crate is to install other Rust crates without recompiling them, after all. Use the dedicated GitHub Action instead: it downloads the binary from GitHub. Compiling the crate takes close to 30 seconds, we should save most of this time (but this only affects the bump.yml workflow).
This is similar to what we do in dpdk-sys's workflows.
=> ci: Install cargo-binstall from dedicated Action

dataplane/src/drivers/kernel.rs
This PR does some cleanup of the multi-threaded kernel driver and allows batched reads in the worker process to more closely match DPDK.  This work is a prerequisite so that I can write a single tokio event wrapper around the pipeline that will work with both the kernel driver and DPDK driver.
=> Batch read packets in kernel worker threads

Cargo.lock, dataplane/Cargo.toml, dataplane/src/drivers/kernel.rs, dataplane/src/drivers/mod.rs, dataplane/src/drivers/tokio_util.rs
* Wrap worker threads in a `tokio` current-thread runtime
* Use `tokio::sync::mpsc` in place of crossbeam so that we can await message
We could use `kanal` in the current implementation, but I think that we'll eventually want to use `tokio::select!` and that will cause problems, so stick to `mpsc` for now until there is a proven performance issue with the channel.
=> Add a tokio wrapper to worker threads in dataplane

.github/workflows/bump.yml
There's no "v1" tag for that image. Let's just pull from the "main" branch, like we do in the worfklow for the dpdk-sys repository.
=> ci: Fix image tag for cargo-binstall

config/src/errors.rs, dataplane/src/drivers/kernel.rs, dataplane/src/packet_processor/egress.rs, dataplane/src/packet_processor/ingress.rs, dataplane/src/packet_processor/ipforward.rs, mgmt/src/processor/confbuild/router.rs, net/src/packet/display.rs, net/src/packet/meta.rs, routing/src/atable/adjacency.rs, routing/src/atable/atablerw.rs, routing/src/atable/resolver.rs, routing/src/config/interface.rs, routing/src/config/mod.rs, routing/src/cpi.rs, routing/src/errors.rs, routing/src/fib/fibgroupstore.rs, routing/src/fib/fibobjects.rs, routing/src/interfaces/iftable.rs, routing/src/interfaces/iftablerw.rs, routing/src/interfaces/interface.rs, routing/src/interfaces/mod.rs, routing/src/rib/nexthop.rs, routing/src/rib/rib2fib.rs, routing/src/rib/vrf.rs, routing/src/rib/vrftable.rs, routing/src/rpc_adapt.rs
Long overdue tech debt payment
=> Refactor InterfaceIndex type

net/src/checksum.rs, net/src/headers/mod.rs
Implement incremental checksum update for IP, TCP, UDP 1s' complement checksums, following the algorithm described in RFC 1624, along with accompanying unit tests.
Contrarily to regular checksum update, we cannot rely on etherparse here, as the crate doesn't support incremental updates at the moment.
This will be useful to update the checksums of an inner IP packet embedded in an ICMP error message, for example, after updating addresses and/or ports for this inner packet.
=> feat(net): Implement incremental checksum update
